// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIZCapi.Data;

namespace SIZCapi.Migrations
{
    [DbContext(typeof(SIZCKontekst))]
    [Migration("20200609204240_SeedingDb")]
    partial class SeedingDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SIZCapi.Models.Alergen", b =>
                {
                    b.Property<int>("AlergenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazwaAlergen")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AlergenID");

                    b.ToTable("Alergen");

                    b.HasData(
                        new
                        {
                            AlergenID = 1,
                            NazwaAlergen = "brak alergenu"
                        },
                        new
                        {
                            AlergenID = 2,
                            NazwaAlergen = "jajka"
                        },
                        new
                        {
                            AlergenID = 3,
                            NazwaAlergen = "mleko"
                        },
                        new
                        {
                            AlergenID = 4,
                            NazwaAlergen = "orzechy"
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.InformacjaAlergen", b =>
                {
                    b.Property<int>("InformacjaAlergenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlergenID")
                        .HasColumnType("int");

                    b.Property<int>("SkladnikID")
                        .HasColumnType("int");

                    b.HasKey("InformacjaAlergenID");

                    b.HasIndex("AlergenID");

                    b.HasIndex("SkladnikID");

                    b.ToTable("InformacjaAlergen");

                    b.HasData(
                        new
                        {
                            InformacjaAlergenID = 1,
                            AlergenID = 1,
                            SkladnikID = 1
                        },
                        new
                        {
                            InformacjaAlergenID = 2,
                            AlergenID = 1,
                            SkladnikID = 2
                        },
                        new
                        {
                            InformacjaAlergenID = 3,
                            AlergenID = 1,
                            SkladnikID = 3
                        },
                        new
                        {
                            InformacjaAlergenID = 4,
                            AlergenID = 1,
                            SkladnikID = 4
                        },
                        new
                        {
                            InformacjaAlergenID = 5,
                            AlergenID = 1,
                            SkladnikID = 5
                        },
                        new
                        {
                            InformacjaAlergenID = 6,
                            AlergenID = 1,
                            SkladnikID = 6
                        },
                        new
                        {
                            InformacjaAlergenID = 7,
                            AlergenID = 1,
                            SkladnikID = 7
                        },
                        new
                        {
                            InformacjaAlergenID = 8,
                            AlergenID = 1,
                            SkladnikID = 8
                        },
                        new
                        {
                            InformacjaAlergenID = 9,
                            AlergenID = 1,
                            SkladnikID = 9
                        },
                        new
                        {
                            InformacjaAlergenID = 10,
                            AlergenID = 1,
                            SkladnikID = 10
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.Klient", b =>
                {
                    b.Property<int>("KlientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdresEmail")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("DataRejestracji")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("HasloHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("HasloSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KodPocztowy")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Miejscowosc")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NrBudynek")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("NrMieszkanie")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("NrTelKomorkowy")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NrTelStacjonarny")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("KlientID");

                    b.ToTable("Klient");

                    b.HasData(
                        new
                        {
                            KlientID = 1,
                            AdresEmail = "jan.kowalski@wp.pl",
                            DataRejestracji = new DateTime(2020, 6, 1, 7, 47, 0, 0, DateTimeKind.Unspecified),
                            HasloHash = new byte[] { 170, 14, 16, 253, 13, 157, 134, 43, 48, 140, 75, 215, 59, 169, 120, 138, 82, 217, 139, 252, 5, 90, 9, 160, 20, 206, 213, 251, 47, 61, 159, 79, 66, 155, 50, 100, 221, 185, 162, 59, 185, 4, 243, 160, 61, 157, 102, 233, 74, 110, 153, 222, 66, 196, 81, 101, 223, 163, 34, 159, 196, 8, 251, 142 },
                            HasloSalt = new byte[] { 57, 147, 159, 78, 240, 174, 91, 78, 175, 87, 138, 32, 26, 0, 227, 176, 42, 174, 114, 205, 185, 168, 23, 40, 50, 251, 174, 40, 129, 38, 239, 213, 18, 121, 125, 204, 154, 199, 177, 11, 172, 198, 182, 165, 104, 105, 123, 42, 204, 36, 40, 177, 131, 167, 192, 169, 14, 205, 44, 24, 133, 59, 52, 51, 200, 234, 110, 97, 247, 197, 41, 183, 247, 109, 186, 54, 120, 225, 140, 147, 60, 61, 131, 107, 51, 143, 242, 131, 196, 183, 235, 200, 247, 53, 180, 244, 248, 108, 162, 89, 238, 238, 232, 2, 27, 212, 222, 229, 25, 136, 221, 33, 131, 30, 7, 11, 143, 43, 91, 94, 106, 85, 91, 106, 236, 152, 244, 82 },
                            Imie = "Jan",
                            KodPocztowy = "01234",
                            Miejscowosc = "Warszawa",
                            Nazwisko = "Kowalski",
                            NrBudynek = "1",
                            NrMieszkanie = "2",
                            NrTelKomorkowy = "123456789",
                            NrTelStacjonarny = "221234567",
                            Ulica = "Długa"
                        },
                        new
                        {
                            KlientID = 2,
                            AdresEmail = "elzbieta.zalewska@gmail.com",
                            DataRejestracji = new DateTime(2020, 6, 2, 14, 37, 12, 0, DateTimeKind.Unspecified),
                            HasloHash = new byte[] { 18, 36, 52, 123, 205, 72, 214, 20, 74, 211, 235, 254, 111, 99, 232, 29, 146, 93, 180, 191, 10, 112, 18, 181, 152, 88, 1, 51, 194, 124, 173, 239, 119, 16, 157, 126, 97, 100, 92, 234, 193, 229, 126, 112, 232, 77, 101, 228, 168, 99, 34, 247, 40, 91, 38, 253, 197, 54, 118, 193, 38, 204, 192, 36 },
                            HasloSalt = new byte[] { 121, 250, 95, 167, 215, 164, 32, 145, 75, 6, 34, 7, 158, 143, 122, 77, 239, 130, 232, 140, 126, 1, 177, 147, 186, 120, 55, 84, 180, 96, 38, 100, 59, 1, 33, 68, 71, 128, 149, 232, 106, 230, 149, 211, 37, 153, 17, 29, 193, 95, 248, 51, 135, 141, 43, 200, 3, 162, 107, 229, 164, 205, 40, 145, 197, 195, 204, 21, 78, 37, 98, 71, 37, 222, 97, 242, 226, 126, 123, 152, 156, 48, 244, 240, 22, 42, 203, 7, 99, 196, 193, 116, 177, 43, 89, 242, 125, 83, 139, 181, 60, 148, 33, 145, 153, 192, 177, 57, 147, 115, 79, 13, 49, 246, 156, 163, 253, 204, 31, 149, 251, 52, 79, 207, 2, 99, 159, 119 },
                            Imie = "Elżbieta",
                            KodPocztowy = "43210",
                            Miejscowosc = "Kraków",
                            Nazwisko = "Zalewska",
                            NrBudynek = "17a",
                            NrMieszkanie = "-",
                            NrTelKomorkowy = "987654321",
                            NrTelStacjonarny = "-",
                            Ulica = "Krótka"
                        },
                        new
                        {
                            KlientID = 3,
                            AdresEmail = "marcin.nowak@onet.pl",
                            DataRejestracji = new DateTime(2020, 6, 4, 23, 7, 21, 0, DateTimeKind.Unspecified),
                            HasloHash = new byte[] { 228, 142, 70, 51, 193, 240, 60, 213, 150, 24, 9, 45, 52, 169, 183, 195, 241, 1, 155, 196, 179, 123, 213, 81, 20, 228, 139, 70, 176, 175, 98, 233, 189, 242, 102, 237, 184, 172, 195, 72, 118, 214, 60, 239, 54, 164, 112, 36, 153, 172, 20, 75, 12, 210, 232, 124, 29, 140, 149, 195, 86, 27, 220, 2 },
                            HasloSalt = new byte[] { 71, 24, 1, 98, 114, 136, 246, 47, 189, 32, 68, 45, 131, 116, 137, 177, 137, 41, 145, 255, 120, 163, 73, 97, 172, 5, 152, 126, 5, 118, 209, 62, 113, 115, 98, 119, 14, 89, 190, 87, 110, 104, 235, 99, 35, 246, 161, 247, 3, 1, 7, 255, 99, 123, 25, 205, 64, 82, 11, 195, 168, 108, 55, 80, 127, 18, 8, 14, 64, 1, 184, 118, 206, 196, 85, 114, 167, 180, 68, 89, 181, 252, 37, 50, 248, 30, 120, 76, 124, 232, 210, 46, 118, 100, 133, 153, 28, 47, 0, 39, 122, 61, 29, 119, 173, 165, 39, 129, 60, 126, 30, 120, 3, 10, 228, 74, 97, 58, 109, 234, 159, 125, 54, 218, 158, 104, 38, 216 },
                            Imie = "Marcin",
                            KodPocztowy = "11222",
                            Miejscowosc = "Gdańsk",
                            Nazwisko = "Nowak",
                            NrBudynek = "12",
                            NrMieszkanie = "2",
                            NrTelKomorkowy = "-",
                            NrTelStacjonarny = "221112233",
                            Ulica = "Szeroka"
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.PlatnoscTyp", b =>
                {
                    b.Property<int>("PlatnoscTypID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazwaPlatnosc")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PlatnoscTypID");

                    b.ToTable("PlatnoscTyp");

                    b.HasData(
                        new
                        {
                            PlatnoscTypID = 1,
                            NazwaPlatnosc = "gotówka"
                        },
                        new
                        {
                            PlatnoscTypID = 2,
                            NazwaPlatnosc = "blik"
                        },
                        new
                        {
                            PlatnoscTypID = 3,
                            NazwaPlatnosc = "przelew"
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.PozycjaMenu", b =>
                {
                    b.Property<int>("PozycjaMenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cena")
                        .HasColumnType("money");

                    b.Property<string>("NazwaPozycja")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ObrazekUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PozycjaMenuID");

                    b.ToTable("PozycjaMenu");

                    b.HasData(
                        new
                        {
                            PozycjaMenuID = 1,
                            Cena = 26.50m,
                            NazwaPozycja = "Dieta Vege",
                            ObrazekUrl = "https://i.ibb.co/ChJDspJ/dieta-Vege.png",
                            Opis = "Pozycja dla wegetarian, bogata w produkty roślinne"
                        },
                        new
                        {
                            PozycjaMenuID = 2,
                            Cena = 25.50m,
                            NazwaPozycja = "Dieta Light",
                            ObrazekUrl = "https://i.ibb.co/kgPxXXX/dieta-Light.png",
                            Opis = "Pozycja dla osób odchudzjących się, bogata w błonnik"
                        },
                        new
                        {
                            PozycjaMenuID = 3,
                            Cena = 27.50m,
                            NazwaPozycja = "Dieta Sport",
                            ObrazekUrl = "https://i.ibb.co/CBTgwTZ/dieta-Sport.png",
                            Opis = "Pozycja dla osób trenujących, bogata w białko"
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.Pracownik", b =>
                {
                    b.Property<int>("PracownikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("HasloHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("HasloSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PracownikRolaID")
                        .HasColumnType("int");

                    b.HasKey("PracownikID");

                    b.HasIndex("PracownikRolaID");

                    b.ToTable("Pracownik");

                    b.HasData(
                        new
                        {
                            PracownikID = 1,
                            HasloHash = new byte[] { 88, 99, 250, 96, 27, 39, 98, 124, 132, 199, 254, 30, 29, 99, 239, 84, 144, 182, 200, 157, 156, 90, 135, 109, 176, 119, 173, 132, 255, 225, 12, 45, 71, 17, 104, 111, 100, 106, 173, 79, 125, 214, 140, 153, 119, 211, 243, 97, 95, 120, 199, 162, 250, 212, 48, 189, 141, 96, 14, 29, 174, 66, 176, 134 },
                            HasloSalt = new byte[] { 219, 202, 46, 140, 220, 31, 157, 188, 85, 16, 198, 227, 251, 3, 95, 238, 71, 171, 192, 35, 171, 16, 244, 167, 169, 97, 162, 13, 23, 14, 68, 45, 249, 177, 92, 71, 74, 166, 80, 107, 49, 91, 19, 159, 121, 26, 157, 156, 57, 238, 193, 81, 245, 170, 146, 120, 98, 155, 167, 236, 189, 85, 239, 119, 241, 125, 98, 144, 198, 175, 100, 107, 171, 5, 174, 74, 121, 92, 79, 168, 187, 237, 130, 85, 200, 57, 241, 170, 190, 139, 222, 238, 91, 161, 238, 181, 200, 237, 119, 64, 24, 5, 151, 57, 137, 145, 154, 69, 63, 207, 179, 79, 132, 168, 74, 36, 46, 131, 43, 222, 236, 49, 56, 132, 221, 9, 12, 52 },
                            Login = "kucharz1",
                            PracownikRolaID = 1
                        },
                        new
                        {
                            PracownikID = 2,
                            HasloHash = new byte[] { 246, 105, 54, 49, 83, 189, 240, 143, 129, 207, 253, 160, 90, 103, 163, 111, 24, 56, 85, 229, 83, 157, 148, 83, 178, 89, 218, 97, 220, 233, 153, 94, 154, 29, 173, 113, 146, 62, 70, 156, 163, 109, 191, 50, 77, 53, 183, 75, 90, 16, 90, 80, 156, 154, 10, 117, 21, 117, 61, 67, 45, 37, 8, 186 },
                            HasloSalt = new byte[] { 219, 95, 92, 132, 78, 74, 73, 252, 13, 93, 146, 254, 134, 37, 44, 237, 242, 70, 119, 203, 194, 88, 131, 56, 11, 216, 218, 220, 182, 89, 77, 50, 161, 204, 111, 74, 33, 100, 236, 50, 64, 116, 80, 34, 216, 97, 140, 38, 164, 136, 33, 152, 211, 119, 83, 162, 191, 220, 173, 39, 155, 218, 5, 246, 234, 235, 242, 244, 131, 198, 61, 117, 205, 7, 15, 175, 148, 98, 24, 183, 246, 183, 91, 59, 175, 125, 208, 201, 200, 136, 109, 2, 230, 236, 131, 16, 234, 84, 203, 213, 243, 17, 27, 100, 41, 190, 42, 112, 144, 214, 206, 43, 214, 104, 171, 55, 139, 211, 207, 228, 213, 66, 118, 145, 85, 137, 247, 121 },
                            Login = "dostawca1",
                            PracownikRolaID = 2
                        },
                        new
                        {
                            PracownikID = 3,
                            HasloHash = new byte[] { 137, 224, 224, 5, 149, 165, 6, 146, 210, 239, 220, 213, 163, 138, 82, 240, 107, 213, 155, 202, 114, 57, 11, 107, 26, 240, 137, 36, 133, 156, 139, 41, 17, 53, 27, 188, 223, 24, 21, 17, 0, 63, 151, 180, 34, 162, 117, 164, 88, 108, 205, 130, 208, 241, 98, 255, 219, 247, 94, 39, 237, 128, 213, 111 },
                            HasloSalt = new byte[] { 42, 222, 3, 39, 252, 148, 22, 236, 185, 162, 251, 30, 247, 103, 142, 30, 76, 165, 241, 85, 232, 146, 25, 136, 168, 134, 180, 74, 182, 2, 74, 195, 183, 111, 141, 171, 30, 57, 163, 81, 250, 14, 86, 47, 226, 123, 185, 187, 37, 25, 56, 139, 88, 96, 43, 86, 236, 250, 76, 149, 101, 107, 115, 0, 173, 242, 138, 22, 116, 166, 91, 226, 252, 252, 62, 144, 28, 186, 49, 149, 30, 103, 7, 104, 103, 93, 29, 45, 156, 100, 124, 39, 181, 89, 39, 214, 85, 33, 101, 241, 38, 249, 41, 20, 20, 143, 76, 189, 187, 250, 92, 118, 206, 217, 11, 73, 147, 50, 145, 253, 248, 96, 32, 126, 255, 51, 76, 146 },
                            Login = "administartor1",
                            PracownikRolaID = 3
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.PracownikRola", b =>
                {
                    b.Property<int>("PracownikRolaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazwaRola")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PracownikRolaID");

                    b.ToTable("PracownikRola");

                    b.HasData(
                        new
                        {
                            PracownikRolaID = 1,
                            NazwaRola = "kucharz"
                        },
                        new
                        {
                            PracownikRolaID = 2,
                            NazwaRola = "dostawca"
                        },
                        new
                        {
                            PracownikRolaID = 3,
                            NazwaRola = "administrator"
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.Skladnik", b =>
                {
                    b.Property<int>("SkladnikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CzyWeganski")
                        .HasColumnType("bit");

                    b.Property<bool>("CzyWegetarianski")
                        .HasColumnType("bit");

                    b.Property<float>("MasaSkladnik")
                        .HasColumnType("real");

                    b.Property<string>("NazwaSkladnik")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PozycjaMenuID")
                        .HasColumnType("int");

                    b.HasKey("SkladnikID");

                    b.HasIndex("PozycjaMenuID");

                    b.ToTable("Skladnik");

                    b.HasData(
                        new
                        {
                            SkladnikID = 1,
                            CzyWeganski = true,
                            CzyWegetarianski = true,
                            MasaSkladnik = 42f,
                            NazwaSkladnik = "awokado",
                            PozycjaMenuID = 1
                        },
                        new
                        {
                            SkladnikID = 2,
                            CzyWeganski = true,
                            CzyWegetarianski = true,
                            MasaSkladnik = 45f,
                            NazwaSkladnik = "marchew",
                            PozycjaMenuID = 1
                        },
                        new
                        {
                            SkladnikID = 3,
                            CzyWeganski = true,
                            CzyWegetarianski = true,
                            MasaSkladnik = 80f,
                            NazwaSkladnik = "soczewica",
                            PozycjaMenuID = 1
                        },
                        new
                        {
                            SkladnikID = 4,
                            CzyWeganski = true,
                            CzyWegetarianski = true,
                            MasaSkladnik = 200f,
                            NazwaSkladnik = "pomidory",
                            PozycjaMenuID = 1
                        },
                        new
                        {
                            SkladnikID = 5,
                            CzyWeganski = false,
                            CzyWegetarianski = false,
                            MasaSkladnik = 142f,
                            NazwaSkladnik = "dorsz gotowany",
                            PozycjaMenuID = 2
                        },
                        new
                        {
                            SkladnikID = 6,
                            CzyWeganski = false,
                            CzyWegetarianski = false,
                            MasaSkladnik = 57f,
                            NazwaSkladnik = "brokuły",
                            PozycjaMenuID = 2
                        },
                        new
                        {
                            SkladnikID = 7,
                            CzyWeganski = true,
                            CzyWegetarianski = true,
                            MasaSkladnik = 68f,
                            NazwaSkladnik = "dziki ryż",
                            PozycjaMenuID = 2
                        },
                        new
                        {
                            SkladnikID = 8,
                            CzyWeganski = false,
                            CzyWegetarianski = false,
                            MasaSkladnik = 143f,
                            NazwaSkladnik = "kurczak",
                            PozycjaMenuID = 3
                        },
                        new
                        {
                            SkladnikID = 9,
                            CzyWeganski = true,
                            CzyWegetarianski = true,
                            MasaSkladnik = 153f,
                            NazwaSkladnik = "ziemniaki",
                            PozycjaMenuID = 3
                        },
                        new
                        {
                            SkladnikID = 10,
                            CzyWeganski = true,
                            CzyWegetarianski = true,
                            MasaSkladnik = 63f,
                            NazwaSkladnik = "sałata",
                            PozycjaMenuID = 3
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.SkladnikOdzywczy", b =>
                {
                    b.Property<int>("SkladnikOdzywczyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Kalorycznosc")
                        .HasColumnType("real");

                    b.Property<string>("NazwaSkladnik")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SkladnikOdzywczyID");

                    b.ToTable("SkladnikOdzywczy");

                    b.HasData(
                        new
                        {
                            SkladnikOdzywczyID = 1,
                            Kalorycznosc = 4f,
                            NazwaSkladnik = "białko"
                        },
                        new
                        {
                            SkladnikOdzywczyID = 2,
                            Kalorycznosc = 9f,
                            NazwaSkladnik = "tłuszcz"
                        },
                        new
                        {
                            SkladnikOdzywczyID = 3,
                            Kalorycznosc = 4f,
                            NazwaSkladnik = "węglowodany"
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.WartoscOdzywcza", b =>
                {
                    b.Property<int>("WartoscOdzywczaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SkladnikID")
                        .HasColumnType("int");

                    b.Property<int>("SkladnikOdzywczyID")
                        .HasColumnType("int");

                    b.Property<float>("ZawartoscSkladnikOdzywczy")
                        .HasColumnType("real");

                    b.HasKey("WartoscOdzywczaID");

                    b.HasIndex("SkladnikID");

                    b.HasIndex("SkladnikOdzywczyID");

                    b.ToTable("WartoscOdzywcza");

                    b.HasData(
                        new
                        {
                            WartoscOdzywczaID = 1,
                            SkladnikID = 1,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 15f
                        },
                        new
                        {
                            WartoscOdzywczaID = 2,
                            SkladnikID = 1,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 9f
                        },
                        new
                        {
                            WartoscOdzywczaID = 3,
                            SkladnikID = 1,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 4f
                        },
                        new
                        {
                            WartoscOdzywczaID = 4,
                            SkladnikID = 2,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 0.2f
                        },
                        new
                        {
                            WartoscOdzywczaID = 5,
                            SkladnikID = 2,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 10f
                        },
                        new
                        {
                            WartoscOdzywczaID = 6,
                            SkladnikID = 2,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 0.9f
                        },
                        new
                        {
                            WartoscOdzywczaID = 7,
                            SkladnikID = 3,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 0.4f
                        },
                        new
                        {
                            WartoscOdzywczaID = 8,
                            SkladnikID = 3,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 20f
                        },
                        new
                        {
                            WartoscOdzywczaID = 9,
                            SkladnikID = 3,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 9f
                        },
                        new
                        {
                            WartoscOdzywczaID = 10,
                            SkladnikID = 4,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 0.2f
                        },
                        new
                        {
                            WartoscOdzywczaID = 11,
                            SkladnikID = 4,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 3.9f
                        },
                        new
                        {
                            WartoscOdzywczaID = 12,
                            SkladnikID = 4,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 0.9f
                        },
                        new
                        {
                            WartoscOdzywczaID = 13,
                            SkladnikID = 5,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 0.67f
                        },
                        new
                        {
                            WartoscOdzywczaID = 14,
                            SkladnikID = 5,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 0f
                        },
                        new
                        {
                            WartoscOdzywczaID = 15,
                            SkladnikID = 5,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 17.8f
                        },
                        new
                        {
                            WartoscOdzywczaID = 16,
                            SkladnikID = 6,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 0.4f
                        },
                        new
                        {
                            WartoscOdzywczaID = 17,
                            SkladnikID = 6,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 7f
                        },
                        new
                        {
                            WartoscOdzywczaID = 18,
                            SkladnikID = 6,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 2.8f
                        },
                        new
                        {
                            WartoscOdzywczaID = 19,
                            SkladnikID = 7,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 1.1f
                        },
                        new
                        {
                            WartoscOdzywczaID = 20,
                            SkladnikID = 7,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 75f
                        },
                        new
                        {
                            WartoscOdzywczaID = 21,
                            SkladnikID = 7,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 15f
                        },
                        new
                        {
                            WartoscOdzywczaID = 22,
                            SkladnikID = 8,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 14f
                        },
                        new
                        {
                            WartoscOdzywczaID = 23,
                            SkladnikID = 8,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 0f
                        },
                        new
                        {
                            WartoscOdzywczaID = 24,
                            SkladnikID = 8,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 27f
                        },
                        new
                        {
                            WartoscOdzywczaID = 25,
                            SkladnikID = 9,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 0.1f
                        },
                        new
                        {
                            WartoscOdzywczaID = 26,
                            SkladnikID = 9,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 16.3f
                        },
                        new
                        {
                            WartoscOdzywczaID = 27,
                            SkladnikID = 9,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 1.8f
                        },
                        new
                        {
                            WartoscOdzywczaID = 28,
                            SkladnikID = 10,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 0.2f
                        },
                        new
                        {
                            WartoscOdzywczaID = 29,
                            SkladnikID = 10,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 2.9f
                        },
                        new
                        {
                            WartoscOdzywczaID = 30,
                            SkladnikID = 10,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 1.4f
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.Zamowienie", b =>
                {
                    b.Property<int>("ZamowienieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataRealizacji")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataZlozenia")
                        .HasColumnType("datetime2");

                    b.Property<int>("KlientID")
                        .HasColumnType("int");

                    b.Property<string>("KodPocztowy")
                        .HasColumnType("varchar(5)");

                    b.Property<decimal>("Koszt")
                        .HasColumnType("money");

                    b.Property<string>("Miejscowosc")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NrBudynek")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("NrMieszkanie")
                        .HasColumnType("varchar(15)");

                    b.Property<int>("PlatnoscTypID")
                        .HasColumnType("int");

                    b.Property<int>("PozycjaMenuID")
                        .HasColumnType("int");

                    b.Property<int>("PracownikID")
                        .HasColumnType("int");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ZamowienieStatusID")
                        .HasColumnType("int");

                    b.HasKey("ZamowienieID");

                    b.HasIndex("KlientID");

                    b.HasIndex("PlatnoscTypID");

                    b.HasIndex("PozycjaMenuID");

                    b.HasIndex("PracownikID");

                    b.HasIndex("ZamowienieStatusID");

                    b.ToTable("Zamowienie");

                    b.HasData(
                        new
                        {
                            ZamowienieID = 1,
                            DataRealizacji = new DateTime(2020, 6, 3, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            DataZlozenia = new DateTime(2020, 6, 2, 9, 47, 0, 0, DateTimeKind.Unspecified),
                            KlientID = 1,
                            KodPocztowy = "01234",
                            Koszt = 31.5m,
                            Miejscowosc = "Warszawa",
                            NrBudynek = "1",
                            NrMieszkanie = "2",
                            PlatnoscTypID = 1,
                            PozycjaMenuID = 1,
                            PracownikID = 1,
                            Ulica = "Długa",
                            ZamowienieStatusID = 1
                        },
                        new
                        {
                            ZamowienieID = 2,
                            DataRealizacji = new DateTime(2020, 6, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DataZlozenia = new DateTime(2020, 6, 5, 9, 47, 0, 0, DateTimeKind.Unspecified),
                            KlientID = 2,
                            KodPocztowy = "43210",
                            Koszt = 30.5m,
                            Miejscowosc = "Wrocław",
                            NrBudynek = "14c",
                            NrMieszkanie = "-",
                            PlatnoscTypID = 2,
                            PozycjaMenuID = 2,
                            PracownikID = 1,
                            Ulica = "Miła",
                            ZamowienieStatusID = 3
                        },
                        new
                        {
                            ZamowienieID = 3,
                            DataRealizacji = new DateTime(2020, 6, 4, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            DataZlozenia = new DateTime(2020, 6, 3, 9, 7, 5, 0, DateTimeKind.Unspecified),
                            KlientID = 3,
                            KodPocztowy = "11222",
                            Koszt = 36.5m,
                            Miejscowosc = "Gdańsk",
                            NrBudynek = "12",
                            NrMieszkanie = "2",
                            PlatnoscTypID = 3,
                            PozycjaMenuID = 3,
                            PracownikID = 1,
                            Ulica = "Szeroka",
                            ZamowienieStatusID = 5
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.ZamowienieStatus", b =>
                {
                    b.Property<int>("ZamowienieStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazwaStatus")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ZamowienieStatusID");

                    b.ToTable("ZamowienieStatus");

                    b.HasData(
                        new
                        {
                            ZamowienieStatusID = 1,
                            NazwaStatus = "zamówione"
                        },
                        new
                        {
                            ZamowienieStatusID = 2,
                            NazwaStatus = "w trakcie przygotowywania"
                        },
                        new
                        {
                            ZamowienieStatusID = 3,
                            NazwaStatus = "przygotowane"
                        },
                        new
                        {
                            ZamowienieStatusID = 4,
                            NazwaStatus = "w trakcie dostawy"
                        },
                        new
                        {
                            ZamowienieStatusID = 5,
                            NazwaStatus = "dostarczone"
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.InformacjaAlergen", b =>
                {
                    b.HasOne("SIZCapi.Models.Alergen", "Alergen")
                        .WithMany("InformacjaAlergen")
                        .HasForeignKey("AlergenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIZCapi.Models.Skladnik", "Skladnik")
                        .WithMany("InformacjaAlergen")
                        .HasForeignKey("SkladnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIZCapi.Models.Pracownik", b =>
                {
                    b.HasOne("SIZCapi.Models.PracownikRola", "PracownikRola")
                        .WithMany("Pracownik")
                        .HasForeignKey("PracownikRolaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIZCapi.Models.Skladnik", b =>
                {
                    b.HasOne("SIZCapi.Models.PozycjaMenu", "PozycjaMenu")
                        .WithMany("Skladnik")
                        .HasForeignKey("PozycjaMenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIZCapi.Models.WartoscOdzywcza", b =>
                {
                    b.HasOne("SIZCapi.Models.Skladnik", "Skladnik")
                        .WithMany("WartoscOdzywcza")
                        .HasForeignKey("SkladnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIZCapi.Models.SkladnikOdzywczy", "SkladnikOdzywczy")
                        .WithMany("WartoscOdzywcza")
                        .HasForeignKey("SkladnikOdzywczyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIZCapi.Models.Zamowienie", b =>
                {
                    b.HasOne("SIZCapi.Models.Klient", "Klient")
                        .WithMany("Zamowienie")
                        .HasForeignKey("KlientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIZCapi.Models.PlatnoscTyp", "PlatnoscTyp")
                        .WithMany("Zamowienie")
                        .HasForeignKey("PlatnoscTypID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIZCapi.Models.PozycjaMenu", "PozycjaMenu")
                        .WithMany("Zamowienie")
                        .HasForeignKey("PozycjaMenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIZCapi.Models.Pracownik", "Pracownik")
                        .WithMany("Zamowienie")
                        .HasForeignKey("PracownikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIZCapi.Models.ZamowienieStatus", "ZamowienieStatus")
                        .WithMany("Zamowienie")
                        .HasForeignKey("ZamowienieStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
