// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIZCapi.Data;

namespace SIZCapi.Migrations
{
    [DbContext(typeof(SIZCKontekst))]
    partial class SIZCKontekstModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SIZCapi.Models.Alergen", b =>
                {
                    b.Property<int>("AlergenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazwaAlergen")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AlergenID");

                    b.ToTable("Alergen");

                    b.HasData(
                        new
                        {
                            AlergenID = 1,
                            NazwaAlergen = "brak alergenu"
                        },
                        new
                        {
                            AlergenID = 2,
                            NazwaAlergen = "jajka"
                        },
                        new
                        {
                            AlergenID = 3,
                            NazwaAlergen = "mleko"
                        },
                        new
                        {
                            AlergenID = 4,
                            NazwaAlergen = "orzechy"
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.InformacjaAlergen", b =>
                {
                    b.Property<int>("InformacjaAlergenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlergenID")
                        .HasColumnType("int");

                    b.Property<int>("SkladnikID")
                        .HasColumnType("int");

                    b.HasKey("InformacjaAlergenID");

                    b.HasIndex("AlergenID");

                    b.HasIndex("SkladnikID");

                    b.ToTable("InformacjaAlergen");

                    b.HasData(
                        new
                        {
                            InformacjaAlergenID = 1,
                            AlergenID = 1,
                            SkladnikID = 1
                        },
                        new
                        {
                            InformacjaAlergenID = 2,
                            AlergenID = 1,
                            SkladnikID = 2
                        },
                        new
                        {
                            InformacjaAlergenID = 3,
                            AlergenID = 1,
                            SkladnikID = 3
                        },
                        new
                        {
                            InformacjaAlergenID = 4,
                            AlergenID = 1,
                            SkladnikID = 4
                        },
                        new
                        {
                            InformacjaAlergenID = 5,
                            AlergenID = 1,
                            SkladnikID = 5
                        },
                        new
                        {
                            InformacjaAlergenID = 6,
                            AlergenID = 1,
                            SkladnikID = 6
                        },
                        new
                        {
                            InformacjaAlergenID = 7,
                            AlergenID = 1,
                            SkladnikID = 7
                        },
                        new
                        {
                            InformacjaAlergenID = 8,
                            AlergenID = 1,
                            SkladnikID = 8
                        },
                        new
                        {
                            InformacjaAlergenID = 9,
                            AlergenID = 1,
                            SkladnikID = 9
                        },
                        new
                        {
                            InformacjaAlergenID = 10,
                            AlergenID = 1,
                            SkladnikID = 10
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.Klient", b =>
                {
                    b.Property<int>("KlientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdresEmail")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("DataRejestracji")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("HasloHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("HasloSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KodPocztowy")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Miejscowosc")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NrBudynek")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("NrMieszkanie")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("NrTelKomorkowy")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NrTelStacjonarny")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("KlientID");

                    b.ToTable("Klient");

                    b.HasData(
                        new
                        {
                            KlientID = 1,
                            AdresEmail = "hubertniewiatowski@outlook.com",
                            DataRejestracji = new DateTime(2020, 6, 1, 11, 47, 3, 0, DateTimeKind.Unspecified),
                            HasloHash = new byte[] { 191, 69, 151, 158, 145, 119, 85, 164, 226, 40, 100, 18, 254, 166, 89, 27, 198, 17, 209, 160, 95, 170, 161, 192, 247, 118, 62, 92, 35, 26, 162, 182, 145, 226, 176, 193, 193, 197, 76, 215, 158, 1, 238, 46, 80, 154, 1, 140, 207, 186, 168, 160, 148, 31, 10, 223, 101, 86, 157, 37, 206, 185, 20, 181 },
                            HasloSalt = new byte[] { 28, 127, 34, 243, 143, 102, 71, 201, 216, 88, 100, 243, 159, 147, 112, 211, 243, 122, 142, 17, 213, 101, 107, 187, 178, 185, 12, 103, 125, 75, 173, 157, 152, 119, 124, 142, 117, 124, 32, 210, 118, 240, 30, 193, 213, 36, 182, 219, 93, 154, 134, 235, 56, 4, 253, 236, 82, 55, 1, 34, 173, 71, 129, 193, 74, 97, 29, 176, 160, 81, 83, 162, 27, 16, 105, 188, 198, 165, 47, 11, 58, 148, 32, 233, 227, 212, 166, 250, 20, 234, 66, 87, 85, 135, 178, 200, 31, 228, 213, 107, 194, 52, 205, 42, 159, 117, 208, 44, 237, 129, 242, 169, 241, 223, 211, 170, 220, 203, 83, 126, 59, 118, 25, 82, 201, 62, 161, 112 },
                            Imie = "Jan",
                            KodPocztowy = "01234",
                            Miejscowosc = "Warszawa",
                            Nazwisko = "Kowalski",
                            NrBudynek = "1",
                            NrMieszkanie = "2",
                            NrTelKomorkowy = "123456789",
                            NrTelStacjonarny = "221234567",
                            Ulica = "Długa"
                        },
                        new
                        {
                            KlientID = 2,
                            AdresEmail = "hubertniewiatowski@outlook.com",
                            DataRejestracji = new DateTime(2020, 6, 3, 14, 58, 12, 0, DateTimeKind.Unspecified),
                            HasloHash = new byte[] { 63, 48, 166, 227, 159, 93, 188, 138, 251, 188, 127, 202, 31, 110, 184, 173, 94, 131, 53, 206, 9, 231, 235, 105, 118, 75, 20, 254, 95, 108, 122, 91, 156, 14, 219, 74, 146, 64, 147, 97, 105, 14, 67, 161, 212, 140, 216, 29, 194, 153, 17, 30, 247, 183, 26, 238, 77, 83, 166, 91, 11, 67, 255, 73 },
                            HasloSalt = new byte[] { 6, 111, 19, 185, 214, 10, 203, 233, 16, 41, 25, 102, 51, 188, 15, 192, 234, 105, 71, 174, 39, 76, 222, 147, 33, 253, 17, 162, 189, 46, 116, 148, 239, 104, 247, 165, 205, 127, 148, 65, 197, 216, 184, 54, 229, 164, 120, 126, 45, 199, 33, 198, 250, 190, 110, 219, 250, 194, 9, 153, 225, 113, 232, 243, 138, 194, 243, 105, 192, 166, 114, 220, 56, 182, 253, 208, 234, 31, 125, 196, 120, 145, 214, 203, 244, 3, 248, 85, 223, 183, 91, 207, 216, 138, 159, 247, 176, 199, 103, 54, 225, 39, 132, 211, 184, 177, 73, 220, 192, 37, 18, 61, 205, 226, 226, 117, 2, 30, 114, 195, 185, 73, 31, 196, 20, 31, 65, 241 },
                            Imie = "Elżbieta",
                            KodPocztowy = "43210",
                            Miejscowosc = "Kraków",
                            Nazwisko = "Zalewska",
                            NrBudynek = "17a",
                            NrMieszkanie = "-",
                            NrTelKomorkowy = "987654321",
                            NrTelStacjonarny = "-",
                            Ulica = "Krótka"
                        },
                        new
                        {
                            KlientID = 3,
                            AdresEmail = "hubertniewiatowski@outlook.com",
                            DataRejestracji = new DateTime(2020, 6, 7, 23, 7, 21, 0, DateTimeKind.Unspecified),
                            HasloHash = new byte[] { 136, 76, 253, 209, 225, 136, 74, 97, 133, 15, 50, 23, 37, 209, 54, 91, 79, 102, 79, 163, 95, 150, 14, 253, 11, 149, 18, 14, 143, 114, 38, 82, 104, 247, 89, 160, 145, 8, 103, 110, 206, 250, 12, 24, 9, 200, 30, 109, 247, 118, 75, 238, 100, 190, 133, 41, 74, 206, 150, 72, 15, 187, 193, 146 },
                            HasloSalt = new byte[] { 47, 18, 235, 93, 253, 73, 226, 183, 163, 119, 249, 224, 3, 107, 208, 195, 91, 228, 115, 133, 188, 94, 249, 94, 121, 106, 209, 196, 168, 185, 168, 254, 16, 170, 43, 160, 67, 222, 78, 187, 0, 51, 66, 132, 223, 128, 131, 14, 137, 240, 39, 117, 57, 136, 45, 153, 238, 137, 161, 100, 10, 244, 56, 21, 19, 4, 54, 160, 112, 76, 95, 199, 65, 56, 109, 167, 21, 6, 158, 53, 237, 177, 18, 102, 208, 243, 252, 248, 53, 60, 211, 93, 41, 57, 28, 189, 159, 209, 208, 204, 223, 210, 32, 182, 160, 77, 54, 83, 61, 69, 181, 97, 228, 117, 115, 218, 89, 27, 198, 73, 11, 16, 47, 3, 191, 133, 15, 26 },
                            Imie = "Marcin",
                            KodPocztowy = "11222",
                            Miejscowosc = "Gdańsk",
                            Nazwisko = "Nowak",
                            NrBudynek = "12",
                            NrMieszkanie = "2",
                            NrTelKomorkowy = "-",
                            NrTelStacjonarny = "221112233",
                            Ulica = "Szeroka"
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.PlatnoscTyp", b =>
                {
                    b.Property<int>("PlatnoscTypID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazwaPlatnosc")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PlatnoscTypID");

                    b.ToTable("PlatnoscTyp");

                    b.HasData(
                        new
                        {
                            PlatnoscTypID = 1,
                            NazwaPlatnosc = "gotówka"
                        },
                        new
                        {
                            PlatnoscTypID = 2,
                            NazwaPlatnosc = "blik"
                        },
                        new
                        {
                            PlatnoscTypID = 3,
                            NazwaPlatnosc = "przelew"
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.PozycjaMenu", b =>
                {
                    b.Property<int>("PozycjaMenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cena")
                        .HasColumnType("money");

                    b.Property<string>("NazwaPozycja")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ObrazekUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PozycjaMenuID");

                    b.ToTable("PozycjaMenu");

                    b.HasData(
                        new
                        {
                            PozycjaMenuID = 1,
                            Cena = 26.50m,
                            NazwaPozycja = "Dieta Vege",
                            ObrazekUrl = "https://i.ibb.co/ChJDspJ/dieta-Vege.png",
                            Opis = "Pozycja dla wegetarian, bogata w produkty roślinne"
                        },
                        new
                        {
                            PozycjaMenuID = 2,
                            Cena = 25.50m,
                            NazwaPozycja = "Dieta Light",
                            ObrazekUrl = "https://i.ibb.co/kgPxXXX/dieta-Light.png",
                            Opis = "Pozycja dla osób odchudzjących się, bogata w błonnik"
                        },
                        new
                        {
                            PozycjaMenuID = 3,
                            Cena = 27.50m,
                            NazwaPozycja = "Dieta Sport",
                            ObrazekUrl = "https://i.ibb.co/CBTgwTZ/dieta-Sport.png",
                            Opis = "Pozycja dla osób trenujących, bogata w białko"
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.Pracownik", b =>
                {
                    b.Property<int>("PracownikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("HasloHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("HasloSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PracownikRolaID")
                        .HasColumnType("int");

                    b.HasKey("PracownikID");

                    b.HasIndex("PracownikRolaID");

                    b.ToTable("Pracownik");

                    b.HasData(
                        new
                        {
                            PracownikID = 1,
                            HasloHash = new byte[] { 7, 105, 98, 62, 141, 60, 221, 91, 173, 215, 198, 163, 53, 145, 84, 115, 160, 70, 252, 158, 196, 104, 249, 18, 240, 75, 36, 93, 87, 106, 42, 207, 250, 5, 245, 139, 198, 18, 33, 83, 189, 35, 209, 0, 87, 95, 207, 134, 191, 43, 205, 208, 114, 217, 126, 111, 124, 186, 79, 206, 250, 13, 191, 10 },
                            HasloSalt = new byte[] { 4, 51, 154, 67, 114, 118, 41, 195, 215, 185, 114, 245, 167, 101, 38, 189, 221, 226, 126, 131, 38, 12, 121, 85, 182, 109, 196, 207, 50, 136, 62, 178, 49, 45, 122, 217, 3, 239, 61, 54, 206, 78, 222, 229, 85, 137, 98, 117, 30, 251, 156, 140, 198, 55, 232, 57, 251, 157, 151, 196, 189, 69, 48, 169, 209, 99, 50, 130, 48, 200, 71, 157, 230, 227, 218, 33, 152, 79, 229, 66, 147, 241, 170, 36, 47, 95, 153, 15, 129, 93, 159, 248, 4, 163, 25, 63, 73, 141, 218, 53, 133, 56, 187, 169, 199, 73, 63, 253, 36, 46, 247, 187, 173, 26, 71, 93, 59, 1, 109, 190, 222, 63, 236, 38, 228, 100, 171, 0 },
                            Login = "kucharz1",
                            PracownikRolaID = 1
                        },
                        new
                        {
                            PracownikID = 2,
                            HasloHash = new byte[] { 35, 150, 89, 149, 171, 157, 179, 242, 156, 136, 96, 162, 52, 134, 253, 32, 22, 85, 9, 96, 51, 105, 253, 162, 178, 22, 247, 148, 195, 31, 19, 68, 114, 127, 132, 29, 135, 42, 194, 170, 247, 196, 51, 118, 85, 211, 34, 121, 62, 67, 109, 8, 119, 140, 239, 215, 241, 57, 28, 182, 210, 127, 63, 21 },
                            HasloSalt = new byte[] { 110, 60, 30, 221, 242, 167, 132, 128, 71, 93, 205, 44, 186, 42, 180, 177, 144, 241, 50, 151, 55, 36, 251, 10, 3, 4, 185, 162, 191, 89, 49, 139, 213, 71, 221, 165, 42, 110, 74, 92, 169, 192, 9, 47, 73, 253, 189, 86, 37, 155, 25, 142, 104, 20, 209, 239, 137, 179, 118, 7, 200, 70, 81, 194, 158, 45, 131, 191, 41, 154, 201, 113, 227, 236, 31, 47, 55, 112, 104, 65, 233, 252, 137, 221, 59, 216, 120, 47, 2, 64, 186, 221, 199, 79, 136, 14, 148, 117, 116, 129, 208, 241, 155, 211, 240, 9, 36, 22, 196, 232, 14, 151, 169, 130, 226, 175, 151, 182, 135, 60, 246, 197, 134, 48, 39, 159, 75, 10 },
                            Login = "dostawca1",
                            PracownikRolaID = 2
                        },
                        new
                        {
                            PracownikID = 3,
                            HasloHash = new byte[] { 167, 131, 196, 223, 23, 232, 249, 147, 143, 26, 20, 18, 74, 119, 195, 30, 49, 181, 223, 42, 4, 15, 160, 218, 175, 116, 138, 64, 65, 93, 151, 132, 98, 102, 250, 72, 190, 95, 26, 24, 100, 245, 197, 105, 246, 189, 29, 89, 165, 226, 77, 81, 101, 18, 105, 93, 20, 72, 27, 139, 94, 199, 54, 9 },
                            HasloSalt = new byte[] { 238, 221, 161, 58, 121, 3, 204, 246, 17, 201, 254, 215, 7, 11, 115, 57, 68, 241, 58, 188, 71, 151, 108, 97, 104, 118, 221, 123, 2, 157, 239, 63, 216, 216, 173, 215, 167, 14, 41, 89, 25, 187, 61, 19, 85, 40, 161, 196, 202, 239, 62, 226, 40, 99, 25, 46, 172, 129, 201, 233, 68, 186, 127, 237, 44, 218, 157, 204, 63, 156, 80, 153, 238, 196, 40, 124, 5, 173, 231, 126, 205, 108, 234, 82, 145, 123, 240, 121, 152, 24, 190, 118, 87, 172, 32, 34, 164, 132, 131, 163, 177, 53, 162, 203, 97, 90, 76, 16, 232, 226, 5, 26, 254, 245, 44, 183, 177, 66, 98, 32, 236, 147, 153, 184, 91, 221, 94, 153 },
                            Login = "administrator1",
                            PracownikRolaID = 3
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.PracownikRola", b =>
                {
                    b.Property<int>("PracownikRolaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazwaRola")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PracownikRolaID");

                    b.ToTable("PracownikRola");

                    b.HasData(
                        new
                        {
                            PracownikRolaID = 1,
                            NazwaRola = "kucharz"
                        },
                        new
                        {
                            PracownikRolaID = 2,
                            NazwaRola = "dostawca"
                        },
                        new
                        {
                            PracownikRolaID = 3,
                            NazwaRola = "administrator"
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.Skladnik", b =>
                {
                    b.Property<int>("SkladnikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CzyWeganski")
                        .HasColumnType("bit");

                    b.Property<bool>("CzyWegetarianski")
                        .HasColumnType("bit");

                    b.Property<float>("MasaSkladnik")
                        .HasColumnType("real");

                    b.Property<string>("NazwaSkladnik")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PozycjaMenuID")
                        .HasColumnType("int");

                    b.HasKey("SkladnikID");

                    b.HasIndex("PozycjaMenuID");

                    b.ToTable("Skladnik");

                    b.HasData(
                        new
                        {
                            SkladnikID = 1,
                            CzyWeganski = true,
                            CzyWegetarianski = true,
                            MasaSkladnik = 42f,
                            NazwaSkladnik = "awokado",
                            PozycjaMenuID = 1
                        },
                        new
                        {
                            SkladnikID = 2,
                            CzyWeganski = true,
                            CzyWegetarianski = true,
                            MasaSkladnik = 45f,
                            NazwaSkladnik = "marchew",
                            PozycjaMenuID = 1
                        },
                        new
                        {
                            SkladnikID = 3,
                            CzyWeganski = true,
                            CzyWegetarianski = true,
                            MasaSkladnik = 80f,
                            NazwaSkladnik = "soczewica",
                            PozycjaMenuID = 1
                        },
                        new
                        {
                            SkladnikID = 4,
                            CzyWeganski = true,
                            CzyWegetarianski = true,
                            MasaSkladnik = 200f,
                            NazwaSkladnik = "pomidory",
                            PozycjaMenuID = 1
                        },
                        new
                        {
                            SkladnikID = 5,
                            CzyWeganski = false,
                            CzyWegetarianski = false,
                            MasaSkladnik = 142f,
                            NazwaSkladnik = "dorsz gotowany",
                            PozycjaMenuID = 2
                        },
                        new
                        {
                            SkladnikID = 6,
                            CzyWeganski = false,
                            CzyWegetarianski = false,
                            MasaSkladnik = 57f,
                            NazwaSkladnik = "brokuły",
                            PozycjaMenuID = 2
                        },
                        new
                        {
                            SkladnikID = 7,
                            CzyWeganski = true,
                            CzyWegetarianski = true,
                            MasaSkladnik = 68f,
                            NazwaSkladnik = "dziki ryż",
                            PozycjaMenuID = 2
                        },
                        new
                        {
                            SkladnikID = 8,
                            CzyWeganski = false,
                            CzyWegetarianski = false,
                            MasaSkladnik = 143f,
                            NazwaSkladnik = "kurczak",
                            PozycjaMenuID = 3
                        },
                        new
                        {
                            SkladnikID = 9,
                            CzyWeganski = true,
                            CzyWegetarianski = true,
                            MasaSkladnik = 153f,
                            NazwaSkladnik = "ziemniaki",
                            PozycjaMenuID = 3
                        },
                        new
                        {
                            SkladnikID = 10,
                            CzyWeganski = true,
                            CzyWegetarianski = true,
                            MasaSkladnik = 63f,
                            NazwaSkladnik = "sałata",
                            PozycjaMenuID = 3
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.SkladnikOdzywczy", b =>
                {
                    b.Property<int>("SkladnikOdzywczyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Kalorycznosc")
                        .HasColumnType("real");

                    b.Property<string>("NazwaSkladnik")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SkladnikOdzywczyID");

                    b.ToTable("SkladnikOdzywczy");

                    b.HasData(
                        new
                        {
                            SkladnikOdzywczyID = 1,
                            Kalorycznosc = 4f,
                            NazwaSkladnik = "białko"
                        },
                        new
                        {
                            SkladnikOdzywczyID = 2,
                            Kalorycznosc = 9f,
                            NazwaSkladnik = "tłuszcz"
                        },
                        new
                        {
                            SkladnikOdzywczyID = 3,
                            Kalorycznosc = 4f,
                            NazwaSkladnik = "węglowodany"
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.WartoscOdzywcza", b =>
                {
                    b.Property<int>("WartoscOdzywczaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SkladnikID")
                        .HasColumnType("int");

                    b.Property<int>("SkladnikOdzywczyID")
                        .HasColumnType("int");

                    b.Property<float>("ZawartoscSkladnikOdzywczy")
                        .HasColumnType("real");

                    b.HasKey("WartoscOdzywczaID");

                    b.HasIndex("SkladnikID");

                    b.HasIndex("SkladnikOdzywczyID");

                    b.ToTable("WartoscOdzywcza");

                    b.HasData(
                        new
                        {
                            WartoscOdzywczaID = 1,
                            SkladnikID = 1,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 15f
                        },
                        new
                        {
                            WartoscOdzywczaID = 2,
                            SkladnikID = 1,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 9f
                        },
                        new
                        {
                            WartoscOdzywczaID = 3,
                            SkladnikID = 1,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 4f
                        },
                        new
                        {
                            WartoscOdzywczaID = 4,
                            SkladnikID = 2,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 0.2f
                        },
                        new
                        {
                            WartoscOdzywczaID = 5,
                            SkladnikID = 2,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 10f
                        },
                        new
                        {
                            WartoscOdzywczaID = 6,
                            SkladnikID = 2,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 0.9f
                        },
                        new
                        {
                            WartoscOdzywczaID = 7,
                            SkladnikID = 3,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 0.4f
                        },
                        new
                        {
                            WartoscOdzywczaID = 8,
                            SkladnikID = 3,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 20f
                        },
                        new
                        {
                            WartoscOdzywczaID = 9,
                            SkladnikID = 3,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 9f
                        },
                        new
                        {
                            WartoscOdzywczaID = 10,
                            SkladnikID = 4,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 0.2f
                        },
                        new
                        {
                            WartoscOdzywczaID = 11,
                            SkladnikID = 4,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 3.9f
                        },
                        new
                        {
                            WartoscOdzywczaID = 12,
                            SkladnikID = 4,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 0.9f
                        },
                        new
                        {
                            WartoscOdzywczaID = 13,
                            SkladnikID = 5,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 0.67f
                        },
                        new
                        {
                            WartoscOdzywczaID = 14,
                            SkladnikID = 5,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 0f
                        },
                        new
                        {
                            WartoscOdzywczaID = 15,
                            SkladnikID = 5,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 17.8f
                        },
                        new
                        {
                            WartoscOdzywczaID = 16,
                            SkladnikID = 6,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 0.4f
                        },
                        new
                        {
                            WartoscOdzywczaID = 17,
                            SkladnikID = 6,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 7f
                        },
                        new
                        {
                            WartoscOdzywczaID = 18,
                            SkladnikID = 6,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 2.8f
                        },
                        new
                        {
                            WartoscOdzywczaID = 19,
                            SkladnikID = 7,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 1.1f
                        },
                        new
                        {
                            WartoscOdzywczaID = 20,
                            SkladnikID = 7,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 75f
                        },
                        new
                        {
                            WartoscOdzywczaID = 21,
                            SkladnikID = 7,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 15f
                        },
                        new
                        {
                            WartoscOdzywczaID = 22,
                            SkladnikID = 8,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 14f
                        },
                        new
                        {
                            WartoscOdzywczaID = 23,
                            SkladnikID = 8,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 0f
                        },
                        new
                        {
                            WartoscOdzywczaID = 24,
                            SkladnikID = 8,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 27f
                        },
                        new
                        {
                            WartoscOdzywczaID = 25,
                            SkladnikID = 9,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 0.1f
                        },
                        new
                        {
                            WartoscOdzywczaID = 26,
                            SkladnikID = 9,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 16.3f
                        },
                        new
                        {
                            WartoscOdzywczaID = 27,
                            SkladnikID = 9,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 1.8f
                        },
                        new
                        {
                            WartoscOdzywczaID = 28,
                            SkladnikID = 10,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 0.2f
                        },
                        new
                        {
                            WartoscOdzywczaID = 29,
                            SkladnikID = 10,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 2.9f
                        },
                        new
                        {
                            WartoscOdzywczaID = 30,
                            SkladnikID = 10,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 1.4f
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.Zamowienie", b =>
                {
                    b.Property<int>("ZamowienieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataRealizacji")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataZlozenia")
                        .HasColumnType("datetime2");

                    b.Property<int>("KlientID")
                        .HasColumnType("int");

                    b.Property<string>("KodPocztowy")
                        .HasColumnType("varchar(5)");

                    b.Property<decimal>("Koszt")
                        .HasColumnType("money");

                    b.Property<string>("Miejscowosc")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NrBudynek")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("NrMieszkanie")
                        .HasColumnType("varchar(15)");

                    b.Property<int>("PlatnoscTypID")
                        .HasColumnType("int");

                    b.Property<int>("PozycjaMenuID")
                        .HasColumnType("int");

                    b.Property<int>("PracownikID")
                        .HasColumnType("int");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ZamowienieStatusID")
                        .HasColumnType("int");

                    b.HasKey("ZamowienieID");

                    b.HasIndex("KlientID");

                    b.HasIndex("PlatnoscTypID");

                    b.HasIndex("PozycjaMenuID");

                    b.HasIndex("PracownikID");

                    b.HasIndex("ZamowienieStatusID");

                    b.ToTable("Zamowienie");

                    b.HasData(
                        new
                        {
                            ZamowienieID = 1,
                            DataRealizacji = new DateTime(2020, 6, 3, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            DataZlozenia = new DateTime(2020, 6, 2, 13, 57, 32, 0, DateTimeKind.Unspecified),
                            KlientID = 1,
                            KodPocztowy = "01234",
                            Koszt = 31.5m,
                            Miejscowosc = "Warszawa",
                            NrBudynek = "1",
                            NrMieszkanie = "2",
                            PlatnoscTypID = 1,
                            PozycjaMenuID = 1,
                            PracownikID = 1,
                            Ulica = "Długa",
                            ZamowienieStatusID = 1
                        },
                        new
                        {
                            ZamowienieID = 2,
                            DataRealizacji = new DateTime(2020, 6, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DataZlozenia = new DateTime(2020, 6, 4, 17, 47, 42, 0, DateTimeKind.Unspecified),
                            KlientID = 2,
                            KodPocztowy = "43210",
                            Koszt = 30.5m,
                            Miejscowosc = "Wrocław",
                            NrBudynek = "14c",
                            NrMieszkanie = "-",
                            PlatnoscTypID = 2,
                            PozycjaMenuID = 2,
                            PracownikID = 1,
                            Ulica = "Miła",
                            ZamowienieStatusID = 3
                        },
                        new
                        {
                            ZamowienieID = 3,
                            DataRealizacji = new DateTime(2020, 6, 9, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            DataZlozenia = new DateTime(2020, 6, 8, 9, 7, 5, 0, DateTimeKind.Unspecified),
                            KlientID = 3,
                            KodPocztowy = "11222",
                            Koszt = 36.5m,
                            Miejscowosc = "Gdańsk",
                            NrBudynek = "12",
                            NrMieszkanie = "2",
                            PlatnoscTypID = 3,
                            PozycjaMenuID = 3,
                            PracownikID = 1,
                            Ulica = "Szeroka",
                            ZamowienieStatusID = 5
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.ZamowienieStatus", b =>
                {
                    b.Property<int>("ZamowienieStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazwaStatus")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ZamowienieStatusID");

                    b.ToTable("ZamowienieStatus");

                    b.HasData(
                        new
                        {
                            ZamowienieStatusID = 1,
                            NazwaStatus = "zamówione"
                        },
                        new
                        {
                            ZamowienieStatusID = 2,
                            NazwaStatus = "w trakcie przygotowywania"
                        },
                        new
                        {
                            ZamowienieStatusID = 3,
                            NazwaStatus = "przygotowane"
                        },
                        new
                        {
                            ZamowienieStatusID = 4,
                            NazwaStatus = "w trakcie dostawy"
                        },
                        new
                        {
                            ZamowienieStatusID = 5,
                            NazwaStatus = "dostarczone"
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.InformacjaAlergen", b =>
                {
                    b.HasOne("SIZCapi.Models.Alergen", "Alergen")
                        .WithMany("InformacjaAlergen")
                        .HasForeignKey("AlergenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIZCapi.Models.Skladnik", "Skladnik")
                        .WithMany("InformacjaAlergen")
                        .HasForeignKey("SkladnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIZCapi.Models.Pracownik", b =>
                {
                    b.HasOne("SIZCapi.Models.PracownikRola", "PracownikRola")
                        .WithMany("Pracownik")
                        .HasForeignKey("PracownikRolaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIZCapi.Models.Skladnik", b =>
                {
                    b.HasOne("SIZCapi.Models.PozycjaMenu", "PozycjaMenu")
                        .WithMany("Skladnik")
                        .HasForeignKey("PozycjaMenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIZCapi.Models.WartoscOdzywcza", b =>
                {
                    b.HasOne("SIZCapi.Models.Skladnik", "Skladnik")
                        .WithMany("WartoscOdzywcza")
                        .HasForeignKey("SkladnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIZCapi.Models.SkladnikOdzywczy", "SkladnikOdzywczy")
                        .WithMany("WartoscOdzywcza")
                        .HasForeignKey("SkladnikOdzywczyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIZCapi.Models.Zamowienie", b =>
                {
                    b.HasOne("SIZCapi.Models.Klient", "Klient")
                        .WithMany("Zamowienie")
                        .HasForeignKey("KlientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIZCapi.Models.PlatnoscTyp", "PlatnoscTyp")
                        .WithMany("Zamowienie")
                        .HasForeignKey("PlatnoscTypID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIZCapi.Models.PozycjaMenu", "PozycjaMenu")
                        .WithMany("Zamowienie")
                        .HasForeignKey("PozycjaMenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIZCapi.Models.Pracownik", "Pracownik")
                        .WithMany("Zamowienie")
                        .HasForeignKey("PracownikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIZCapi.Models.ZamowienieStatus", "ZamowienieStatus")
                        .WithMany("Zamowienie")
                        .HasForeignKey("ZamowienieStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
