// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIZCapi.Data;

namespace SIZCapi.Migrations
{
    [DbContext(typeof(SIZCKontekst))]
    partial class SIZCKontekstModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SIZCapi.Models.Alergen", b =>
                {
                    b.Property<int>("AlergenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazwaAlergen")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AlergenID");

                    b.ToTable("Alergen");
                });

            modelBuilder.Entity("SIZCapi.Models.Klient", b =>
                {
                    b.Property<int>("KlientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdresEmail")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("DataRejestracji")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("HasloHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("HasloSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KodPocztowy")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Miejscowosc")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NrBudynek")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("NrMieszkanie")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("NrTelKomorkowy")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NrTelStacjonarny")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("KlientID");

                    b.ToTable("Klient");
                });

            modelBuilder.Entity("SIZCapi.Models.PlatnoscTyp", b =>
                {
                    b.Property<int>("PlatnoscTypID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazwaPlatnosc")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PlatnoscTypID");

                    b.ToTable("PlatnoscTyp");
                });

            modelBuilder.Entity("SIZCapi.Models.PozycjaMenu", b =>
                {
                    b.Property<int>("PozycjaMenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cena")
                        .HasColumnType("money");

                    b.Property<string>("NazwaPozycja")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ObrazekUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PozycjaMenuID");

                    b.ToTable("PozycjaMenu");
                });

            modelBuilder.Entity("SIZCapi.Models.Pracownik", b =>
                {
                    b.Property<int>("PracownikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("HasloHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("HasloSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PracownikRolaID")
                        .HasColumnType("int");

                    b.HasKey("PracownikID");

                    b.HasIndex("PracownikRolaID");

                    b.ToTable("Pracownik");
                });

            modelBuilder.Entity("SIZCapi.Models.PracownikRola", b =>
                {
                    b.Property<int>("PracownikRolaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazwaRola")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PracownikRolaID");

                    b.ToTable("PracownikRola");
                });

            modelBuilder.Entity("SIZCapi.Models.Skladnik", b =>
                {
                    b.Property<int>("SkladnikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlergenID")
                        .HasColumnType("int");

                    b.Property<bool>("CzyWeganski")
                        .HasColumnType("bit");

                    b.Property<bool>("CzyWegetarianski")
                        .HasColumnType("bit");

                    b.Property<float>("MasaSkladnik")
                        .HasColumnType("real");

                    b.Property<float>("MasaWartoscOdzywcza")
                        .HasColumnType("real");

                    b.Property<string>("NazwaSkladnik")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PozycjaMenuID")
                        .HasColumnType("int");

                    b.Property<int>("WartoscOdzywczaID")
                        .HasColumnType("int");

                    b.HasKey("SkladnikID");

                    b.HasIndex("AlergenID");

                    b.HasIndex("PozycjaMenuID");

                    b.HasIndex("WartoscOdzywczaID");

                    b.ToTable("Skladnik");
                });

            modelBuilder.Entity("SIZCapi.Models.WartoscOdzywcza", b =>
                {
                    b.Property<int>("WartoscOdzywczaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Kalorycznosc")
                        .HasColumnType("real");

                    b.Property<string>("NazwaWartoscOdzywcza")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WartoscOdzywczaID");

                    b.ToTable("WartoscOdzywcza");
                });

            modelBuilder.Entity("SIZCapi.Models.Zamowienie", b =>
                {
                    b.Property<int>("ZamowienieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataRealizacji")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataZlozenia")
                        .HasColumnType("datetime2");

                    b.Property<int>("KlientID")
                        .HasColumnType("int");

                    b.Property<string>("KodPocztowy")
                        .HasColumnType("varchar(5)");

                    b.Property<decimal>("Koszt")
                        .HasColumnType("money");

                    b.Property<string>("Miejscowosc")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NrBudynek")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("NrMieszkanie")
                        .HasColumnType("varchar(15)");

                    b.Property<int>("PlatnoscTypID")
                        .HasColumnType("int");

                    b.Property<int>("PozycjaMenuID")
                        .HasColumnType("int");

                    b.Property<int>("PracownikID")
                        .HasColumnType("int");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ZamowienieStatusID")
                        .HasColumnType("int");

                    b.HasKey("ZamowienieID");

                    b.HasIndex("KlientID");

                    b.HasIndex("PlatnoscTypID");

                    b.HasIndex("PozycjaMenuID");

                    b.HasIndex("PracownikID");

                    b.HasIndex("ZamowienieStatusID");

                    b.ToTable("Zamowienie");
                });

            modelBuilder.Entity("SIZCapi.Models.ZamowienieStatus", b =>
                {
                    b.Property<int>("ZamowienieStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazwaStatus")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ZamowienieStatusID");

                    b.ToTable("ZamowienieStatus");
                });

            modelBuilder.Entity("SIZCapi.Models.Pracownik", b =>
                {
                    b.HasOne("SIZCapi.Models.PracownikRola", "PracownikRola")
                        .WithMany("Pracownik")
                        .HasForeignKey("PracownikRolaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIZCapi.Models.Skladnik", b =>
                {
                    b.HasOne("SIZCapi.Models.Alergen", "Alergen")
                        .WithMany("Skladnik")
                        .HasForeignKey("AlergenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIZCapi.Models.PozycjaMenu", "PozycjaMenu")
                        .WithMany("Skladnik")
                        .HasForeignKey("PozycjaMenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIZCapi.Models.WartoscOdzywcza", "WartoscOdzywcza")
                        .WithMany("Skladnik")
                        .HasForeignKey("WartoscOdzywczaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIZCapi.Models.Zamowienie", b =>
                {
                    b.HasOne("SIZCapi.Models.Klient", "Klient")
                        .WithMany("Zamowienie")
                        .HasForeignKey("KlientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIZCapi.Models.PlatnoscTyp", "PlatnoscTyp")
                        .WithMany("Zamowienie")
                        .HasForeignKey("PlatnoscTypID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIZCapi.Models.PozycjaMenu", "PozycjaMenu")
                        .WithMany("Zamowienie")
                        .HasForeignKey("PozycjaMenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIZCapi.Models.Pracownik", "Pracownik")
                        .WithMany("Zamowienie")
                        .HasForeignKey("PracownikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIZCapi.Models.ZamowienieStatus", "ZamowienieStatus")
                        .WithMany("Zamowienie")
                        .HasForeignKey("ZamowienieStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
