// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIZCapi.Data;

namespace SIZCapi.Migrations
{
    [DbContext(typeof(SIZCKontekst))]
    partial class SIZCKontekstModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SIZCapi.Models.Alergen", b =>
                {
                    b.Property<int>("AlergenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazwaAlergen")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AlergenID");

                    b.ToTable("Alergen");

                    b.HasData(
                        new
                        {
                            AlergenID = 1,
                            NazwaAlergen = "brak alergenu"
                        },
                        new
                        {
                            AlergenID = 2,
                            NazwaAlergen = "jajka"
                        },
                        new
                        {
                            AlergenID = 3,
                            NazwaAlergen = "mleko"
                        },
                        new
                        {
                            AlergenID = 4,
                            NazwaAlergen = "orzechy"
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.InformacjaAlergen", b =>
                {
                    b.Property<int>("InformacjaAlergenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlergenID")
                        .HasColumnType("int");

                    b.Property<int>("SkladnikID")
                        .HasColumnType("int");

                    b.HasKey("InformacjaAlergenID");

                    b.HasIndex("AlergenID");

                    b.HasIndex("SkladnikID");

                    b.ToTable("InformacjaAlergen");

                    b.HasData(
                        new
                        {
                            InformacjaAlergenID = 1,
                            AlergenID = 1,
                            SkladnikID = 1
                        },
                        new
                        {
                            InformacjaAlergenID = 2,
                            AlergenID = 1,
                            SkladnikID = 2
                        },
                        new
                        {
                            InformacjaAlergenID = 3,
                            AlergenID = 1,
                            SkladnikID = 3
                        },
                        new
                        {
                            InformacjaAlergenID = 4,
                            AlergenID = 1,
                            SkladnikID = 4
                        },
                        new
                        {
                            InformacjaAlergenID = 5,
                            AlergenID = 1,
                            SkladnikID = 5
                        },
                        new
                        {
                            InformacjaAlergenID = 6,
                            AlergenID = 1,
                            SkladnikID = 6
                        },
                        new
                        {
                            InformacjaAlergenID = 7,
                            AlergenID = 1,
                            SkladnikID = 7
                        },
                        new
                        {
                            InformacjaAlergenID = 8,
                            AlergenID = 1,
                            SkladnikID = 8
                        },
                        new
                        {
                            InformacjaAlergenID = 9,
                            AlergenID = 1,
                            SkladnikID = 9
                        },
                        new
                        {
                            InformacjaAlergenID = 10,
                            AlergenID = 1,
                            SkladnikID = 10
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.Klient", b =>
                {
                    b.Property<int>("KlientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdresEmail")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("DataRejestracji")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("HasloHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("HasloSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KodPocztowy")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Miejscowosc")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NrBudynek")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("NrMieszkanie")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("NrTelKomorkowy")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NrTelStacjonarny")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("KlientID");

                    b.ToTable("Klient");

                    b.HasData(
                        new
                        {
                            KlientID = 1,
                            AdresEmail = "hubertniewiatowski@outlook.com",
                            DataRejestracji = new DateTime(2020, 6, 1, 11, 47, 3, 0, DateTimeKind.Unspecified),
                            HasloHash = new byte[] { 149, 191, 148, 51, 81, 184, 15, 229, 203, 117, 223, 25, 162, 50, 137, 250, 163, 167, 28, 22, 141, 107, 64, 75, 20, 87, 213, 72, 208, 150, 75, 202, 249, 216, 118, 130, 88, 121, 211, 122, 22, 106, 180, 247, 174, 131, 126, 226, 253, 71, 177, 79, 126, 10, 19, 117, 159, 58, 208, 182, 74, 102, 202, 68 },
                            HasloSalt = new byte[] { 237, 70, 77, 182, 240, 176, 216, 2, 86, 183, 167, 29, 151, 173, 234, 224, 180, 22, 118, 37, 69, 131, 175, 126, 98, 99, 130, 1, 9, 199, 116, 49, 159, 93, 6, 248, 137, 226, 237, 125, 26, 88, 190, 104, 67, 62, 92, 119, 64, 177, 149, 105, 26, 39, 226, 65, 106, 48, 89, 240, 4, 90, 120, 130, 244, 246, 25, 181, 104, 85, 226, 116, 35, 29, 65, 25, 17, 43, 60, 111, 36, 84, 225, 180, 37, 13, 246, 124, 174, 7, 131, 22, 25, 231, 130, 200, 212, 251, 224, 12, 120, 239, 43, 128, 203, 249, 25, 143, 214, 83, 14, 161, 192, 35, 206, 207, 108, 203, 19, 177, 109, 161, 133, 89, 231, 231, 145, 150 },
                            Imie = "Jan",
                            KodPocztowy = "01234",
                            Miejscowosc = "Warszawa",
                            Nazwisko = "Kowalski",
                            NrBudynek = "1",
                            NrMieszkanie = "2",
                            NrTelKomorkowy = "123456789",
                            NrTelStacjonarny = "221234567",
                            Ulica = "Długa"
                        },
                        new
                        {
                            KlientID = 2,
                            AdresEmail = "elz.zal@wp.pl",
                            DataRejestracji = new DateTime(2020, 6, 3, 14, 58, 12, 0, DateTimeKind.Unspecified),
                            HasloHash = new byte[] { 79, 94, 226, 122, 123, 205, 45, 57, 1, 239, 95, 213, 157, 145, 89, 38, 250, 96, 238, 140, 215, 241, 146, 13, 56, 188, 212, 53, 133, 200, 25, 208, 48, 107, 30, 171, 31, 53, 185, 245, 205, 212, 230, 147, 33, 142, 136, 234, 97, 229, 192, 192, 253, 231, 183, 11, 23, 6, 190, 152, 161, 31, 168, 133 },
                            HasloSalt = new byte[] { 126, 205, 15, 35, 20, 106, 255, 106, 213, 16, 249, 151, 95, 153, 103, 142, 203, 201, 86, 131, 47, 9, 186, 1, 196, 204, 129, 224, 137, 58, 113, 147, 86, 222, 166, 47, 142, 29, 113, 85, 19, 135, 240, 218, 98, 230, 139, 168, 211, 233, 91, 136, 163, 62, 67, 124, 210, 52, 108, 14, 48, 62, 217, 18, 105, 118, 154, 183, 156, 231, 212, 197, 85, 154, 77, 53, 209, 96, 39, 142, 123, 203, 140, 52, 35, 191, 80, 142, 188, 26, 247, 33, 18, 196, 102, 7, 80, 87, 150, 241, 159, 93, 246, 46, 187, 35, 19, 240, 90, 232, 60, 27, 235, 0, 68, 27, 161, 173, 180, 85, 205, 149, 217, 89, 94, 165, 56, 162 },
                            Imie = "Elżbieta",
                            KodPocztowy = "43210",
                            Miejscowosc = "Kraków",
                            Nazwisko = "Zalewska",
                            NrBudynek = "17a",
                            NrMieszkanie = "-",
                            NrTelKomorkowy = "987654321",
                            NrTelStacjonarny = "-",
                            Ulica = "Krótka"
                        },
                        new
                        {
                            KlientID = 3,
                            AdresEmail = "mar.now@onet.pl",
                            DataRejestracji = new DateTime(2020, 6, 7, 23, 7, 21, 0, DateTimeKind.Unspecified),
                            HasloHash = new byte[] { 113, 196, 224, 66, 169, 1, 126, 46, 137, 97, 48, 104, 154, 41, 236, 235, 52, 112, 168, 1, 103, 192, 174, 216, 192, 21, 12, 220, 56, 93, 211, 16, 122, 25, 49, 90, 85, 171, 92, 248, 212, 202, 176, 94, 27, 153, 67, 10, 36, 188, 236, 77, 142, 118, 66, 148, 75, 194, 98, 117, 37, 179, 91, 208 },
                            HasloSalt = new byte[] { 125, 243, 64, 151, 31, 211, 250, 134, 146, 90, 246, 190, 165, 52, 98, 35, 225, 185, 14, 206, 241, 211, 92, 0, 9, 33, 201, 24, 18, 174, 16, 210, 133, 112, 110, 252, 183, 139, 26, 101, 25, 105, 253, 187, 204, 25, 117, 228, 58, 14, 51, 242, 185, 67, 236, 225, 98, 62, 93, 99, 107, 31, 45, 35, 121, 176, 99, 114, 132, 239, 117, 245, 139, 38, 226, 148, 34, 41, 123, 125, 117, 200, 115, 236, 115, 121, 234, 96, 148, 22, 228, 28, 239, 167, 162, 66, 169, 243, 194, 126, 216, 171, 184, 172, 38, 182, 63, 45, 19, 209, 37, 78, 140, 113, 23, 239, 78, 201, 31, 103, 53, 191, 95, 240, 184, 87, 90, 175 },
                            Imie = "Marcin",
                            KodPocztowy = "11222",
                            Miejscowosc = "Gdańsk",
                            Nazwisko = "Nowak",
                            NrBudynek = "12",
                            NrMieszkanie = "2",
                            NrTelKomorkowy = "-",
                            NrTelStacjonarny = "221112233",
                            Ulica = "Szeroka"
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.PlatnoscTyp", b =>
                {
                    b.Property<int>("PlatnoscTypID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazwaPlatnosc")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PlatnoscTypID");

                    b.ToTable("PlatnoscTyp");

                    b.HasData(
                        new
                        {
                            PlatnoscTypID = 1,
                            NazwaPlatnosc = "gotówka"
                        },
                        new
                        {
                            PlatnoscTypID = 2,
                            NazwaPlatnosc = "blik"
                        },
                        new
                        {
                            PlatnoscTypID = 3,
                            NazwaPlatnosc = "przelew"
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.PozycjaMenu", b =>
                {
                    b.Property<int>("PozycjaMenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cena")
                        .HasColumnType("money");

                    b.Property<string>("NazwaPozycja")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ObrazekUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PozycjaMenuID");

                    b.ToTable("PozycjaMenu");

                    b.HasData(
                        new
                        {
                            PozycjaMenuID = 1,
                            Cena = 26.50m,
                            NazwaPozycja = "Dieta Vege",
                            ObrazekUrl = "https://i.ibb.co/ChJDspJ/dieta-Vege.png",
                            Opis = "Pozycja dla wegetarian, bogata w produkty roślinne"
                        },
                        new
                        {
                            PozycjaMenuID = 2,
                            Cena = 25.50m,
                            NazwaPozycja = "Dieta Light",
                            ObrazekUrl = "https://i.ibb.co/kgPxXXX/dieta-Light.png",
                            Opis = "Pozycja dla osób odchudzjących się, bogata w błonnik"
                        },
                        new
                        {
                            PozycjaMenuID = 3,
                            Cena = 27.50m,
                            NazwaPozycja = "Dieta Sport",
                            ObrazekUrl = "https://i.ibb.co/CBTgwTZ/dieta-Sport.png",
                            Opis = "Pozycja dla osób trenujących, bogata w białko"
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.Pracownik", b =>
                {
                    b.Property<int>("PracownikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("HasloHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("HasloSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PracownikRolaID")
                        .HasColumnType("int");

                    b.HasKey("PracownikID");

                    b.HasIndex("PracownikRolaID");

                    b.ToTable("Pracownik");

                    b.HasData(
                        new
                        {
                            PracownikID = 1,
                            HasloHash = new byte[] { 165, 174, 245, 7, 144, 195, 2, 55, 149, 184, 59, 141, 1, 175, 173, 47, 87, 77, 231, 189, 53, 230, 60, 208, 206, 200, 122, 51, 248, 207, 112, 198, 151, 53, 37, 162, 147, 199, 7, 166, 228, 217, 242, 164, 146, 226, 107, 189, 53, 122, 38, 38, 165, 129, 129, 193, 174, 1, 75, 239, 29, 136, 22, 5 },
                            HasloSalt = new byte[] { 10, 51, 15, 132, 230, 70, 227, 113, 47, 91, 39, 52, 150, 243, 61, 226, 255, 65, 159, 38, 103, 181, 168, 184, 136, 59, 73, 67, 65, 117, 29, 249, 234, 180, 8, 11, 121, 96, 79, 112, 71, 230, 88, 188, 166, 189, 164, 135, 200, 67, 33, 205, 192, 96, 38, 80, 6, 240, 108, 236, 240, 8, 179, 28, 117, 100, 5, 105, 234, 105, 204, 12, 96, 199, 73, 171, 179, 47, 5, 15, 250, 150, 154, 227, 29, 167, 172, 220, 124, 4, 138, 249, 14, 60, 153, 16, 132, 195, 198, 100, 79, 73, 112, 228, 176, 240, 185, 227, 247, 198, 168, 191, 116, 73, 200, 158, 24, 180, 195, 242, 5, 23, 89, 211, 168, 1, 206, 202 },
                            Login = "kucharz1",
                            PracownikRolaID = 1
                        },
                        new
                        {
                            PracownikID = 2,
                            HasloHash = new byte[] { 142, 45, 102, 153, 202, 19, 11, 55, 153, 139, 1, 86, 10, 29, 69, 68, 32, 63, 206, 81, 77, 213, 55, 0, 16, 81, 193, 69, 71, 28, 247, 238, 15, 111, 107, 80, 158, 20, 180, 147, 44, 226, 248, 72, 226, 54, 21, 20, 157, 199, 14, 126, 215, 247, 202, 155, 179, 12, 3, 143, 24, 127, 187, 9 },
                            HasloSalt = new byte[] { 232, 97, 82, 212, 195, 90, 217, 108, 232, 246, 93, 168, 91, 143, 251, 68, 245, 100, 59, 60, 230, 60, 225, 53, 107, 167, 66, 52, 16, 178, 136, 121, 168, 73, 17, 224, 149, 62, 230, 66, 37, 193, 85, 11, 83, 37, 18, 152, 187, 32, 169, 101, 128, 47, 51, 42, 23, 37, 20, 165, 65, 78, 114, 4, 217, 205, 201, 12, 169, 101, 42, 241, 173, 173, 38, 62, 107, 68, 79, 45, 141, 87, 187, 253, 231, 221, 150, 236, 66, 70, 188, 156, 89, 220, 82, 187, 221, 233, 0, 150, 236, 103, 15, 24, 50, 16, 56, 184, 139, 173, 190, 165, 202, 226, 202, 142, 232, 32, 180, 236, 54, 7, 168, 242, 31, 39, 20, 204 },
                            Login = "dostawca1",
                            PracownikRolaID = 2
                        },
                        new
                        {
                            PracownikID = 3,
                            HasloHash = new byte[] { 82, 194, 108, 64, 42, 144, 125, 17, 1, 177, 83, 81, 71, 142, 143, 218, 40, 88, 237, 212, 158, 25, 26, 6, 18, 80, 209, 221, 44, 183, 166, 197, 145, 232, 68, 7, 122, 100, 182, 18, 106, 198, 253, 168, 198, 194, 43, 249, 181, 134, 191, 250, 245, 1, 152, 108, 78, 189, 208, 78, 125, 162, 155, 155 },
                            HasloSalt = new byte[] { 238, 251, 81, 62, 113, 163, 25, 109, 198, 75, 119, 86, 184, 30, 183, 122, 220, 18, 181, 223, 165, 211, 44, 90, 21, 238, 34, 53, 55, 55, 170, 75, 7, 57, 4, 107, 139, 238, 163, 81, 48, 133, 232, 220, 242, 160, 149, 194, 187, 52, 0, 168, 223, 198, 116, 237, 167, 113, 167, 30, 250, 140, 34, 199, 19, 43, 111, 36, 213, 25, 225, 143, 29, 140, 178, 52, 103, 131, 50, 186, 20, 86, 66, 178, 161, 152, 209, 73, 160, 208, 22, 102, 34, 22, 136, 178, 125, 7, 124, 146, 155, 52, 75, 130, 43, 148, 78, 6, 101, 204, 26, 17, 89, 144, 182, 170, 42, 47, 161, 245, 58, 193, 60, 12, 99, 229, 243, 178 },
                            Login = "administrator1",
                            PracownikRolaID = 3
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.PracownikRola", b =>
                {
                    b.Property<int>("PracownikRolaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazwaRola")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PracownikRolaID");

                    b.ToTable("PracownikRola");

                    b.HasData(
                        new
                        {
                            PracownikRolaID = 1,
                            NazwaRola = "kucharz"
                        },
                        new
                        {
                            PracownikRolaID = 2,
                            NazwaRola = "dostawca"
                        },
                        new
                        {
                            PracownikRolaID = 3,
                            NazwaRola = "administrator"
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.Skladnik", b =>
                {
                    b.Property<int>("SkladnikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CzyWeganski")
                        .HasColumnType("bit");

                    b.Property<bool>("CzyWegetarianski")
                        .HasColumnType("bit");

                    b.Property<float>("MasaSkladnik")
                        .HasColumnType("real");

                    b.Property<string>("NazwaSkladnik")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PozycjaMenuID")
                        .HasColumnType("int");

                    b.HasKey("SkladnikID");

                    b.HasIndex("PozycjaMenuID");

                    b.ToTable("Skladnik");

                    b.HasData(
                        new
                        {
                            SkladnikID = 1,
                            CzyWeganski = true,
                            CzyWegetarianski = true,
                            MasaSkladnik = 42f,
                            NazwaSkladnik = "awokado",
                            PozycjaMenuID = 1
                        },
                        new
                        {
                            SkladnikID = 2,
                            CzyWeganski = true,
                            CzyWegetarianski = true,
                            MasaSkladnik = 45f,
                            NazwaSkladnik = "marchew",
                            PozycjaMenuID = 1
                        },
                        new
                        {
                            SkladnikID = 3,
                            CzyWeganski = true,
                            CzyWegetarianski = true,
                            MasaSkladnik = 80f,
                            NazwaSkladnik = "soczewica",
                            PozycjaMenuID = 1
                        },
                        new
                        {
                            SkladnikID = 4,
                            CzyWeganski = true,
                            CzyWegetarianski = true,
                            MasaSkladnik = 200f,
                            NazwaSkladnik = "pomidory",
                            PozycjaMenuID = 1
                        },
                        new
                        {
                            SkladnikID = 5,
                            CzyWeganski = false,
                            CzyWegetarianski = false,
                            MasaSkladnik = 142f,
                            NazwaSkladnik = "dorsz gotowany",
                            PozycjaMenuID = 2
                        },
                        new
                        {
                            SkladnikID = 6,
                            CzyWeganski = false,
                            CzyWegetarianski = false,
                            MasaSkladnik = 57f,
                            NazwaSkladnik = "brokuły",
                            PozycjaMenuID = 2
                        },
                        new
                        {
                            SkladnikID = 7,
                            CzyWeganski = true,
                            CzyWegetarianski = true,
                            MasaSkladnik = 68f,
                            NazwaSkladnik = "dziki ryż",
                            PozycjaMenuID = 2
                        },
                        new
                        {
                            SkladnikID = 8,
                            CzyWeganski = false,
                            CzyWegetarianski = false,
                            MasaSkladnik = 143f,
                            NazwaSkladnik = "kurczak",
                            PozycjaMenuID = 3
                        },
                        new
                        {
                            SkladnikID = 9,
                            CzyWeganski = true,
                            CzyWegetarianski = true,
                            MasaSkladnik = 153f,
                            NazwaSkladnik = "ziemniaki",
                            PozycjaMenuID = 3
                        },
                        new
                        {
                            SkladnikID = 10,
                            CzyWeganski = true,
                            CzyWegetarianski = true,
                            MasaSkladnik = 63f,
                            NazwaSkladnik = "sałata",
                            PozycjaMenuID = 3
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.SkladnikOdzywczy", b =>
                {
                    b.Property<int>("SkladnikOdzywczyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Kalorycznosc")
                        .HasColumnType("real");

                    b.Property<string>("NazwaSkladnik")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SkladnikOdzywczyID");

                    b.ToTable("SkladnikOdzywczy");

                    b.HasData(
                        new
                        {
                            SkladnikOdzywczyID = 1,
                            Kalorycznosc = 4f,
                            NazwaSkladnik = "białko"
                        },
                        new
                        {
                            SkladnikOdzywczyID = 2,
                            Kalorycznosc = 9f,
                            NazwaSkladnik = "tłuszcz"
                        },
                        new
                        {
                            SkladnikOdzywczyID = 3,
                            Kalorycznosc = 4f,
                            NazwaSkladnik = "węglowodany"
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.WartoscOdzywcza", b =>
                {
                    b.Property<int>("WartoscOdzywczaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SkladnikID")
                        .HasColumnType("int");

                    b.Property<int>("SkladnikOdzywczyID")
                        .HasColumnType("int");

                    b.Property<float>("ZawartoscSkladnikOdzywczy")
                        .HasColumnType("real");

                    b.HasKey("WartoscOdzywczaID");

                    b.HasIndex("SkladnikID");

                    b.HasIndex("SkladnikOdzywczyID");

                    b.ToTable("WartoscOdzywcza");

                    b.HasData(
                        new
                        {
                            WartoscOdzywczaID = 1,
                            SkladnikID = 1,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 15f
                        },
                        new
                        {
                            WartoscOdzywczaID = 2,
                            SkladnikID = 1,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 9f
                        },
                        new
                        {
                            WartoscOdzywczaID = 3,
                            SkladnikID = 1,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 4f
                        },
                        new
                        {
                            WartoscOdzywczaID = 4,
                            SkladnikID = 2,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 0.2f
                        },
                        new
                        {
                            WartoscOdzywczaID = 5,
                            SkladnikID = 2,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 10f
                        },
                        new
                        {
                            WartoscOdzywczaID = 6,
                            SkladnikID = 2,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 0.9f
                        },
                        new
                        {
                            WartoscOdzywczaID = 7,
                            SkladnikID = 3,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 0.4f
                        },
                        new
                        {
                            WartoscOdzywczaID = 8,
                            SkladnikID = 3,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 20f
                        },
                        new
                        {
                            WartoscOdzywczaID = 9,
                            SkladnikID = 3,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 9f
                        },
                        new
                        {
                            WartoscOdzywczaID = 10,
                            SkladnikID = 4,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 0.2f
                        },
                        new
                        {
                            WartoscOdzywczaID = 11,
                            SkladnikID = 4,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 3.9f
                        },
                        new
                        {
                            WartoscOdzywczaID = 12,
                            SkladnikID = 4,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 0.9f
                        },
                        new
                        {
                            WartoscOdzywczaID = 13,
                            SkladnikID = 5,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 0.67f
                        },
                        new
                        {
                            WartoscOdzywczaID = 14,
                            SkladnikID = 5,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 0f
                        },
                        new
                        {
                            WartoscOdzywczaID = 15,
                            SkladnikID = 5,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 17.8f
                        },
                        new
                        {
                            WartoscOdzywczaID = 16,
                            SkladnikID = 6,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 0.4f
                        },
                        new
                        {
                            WartoscOdzywczaID = 17,
                            SkladnikID = 6,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 7f
                        },
                        new
                        {
                            WartoscOdzywczaID = 18,
                            SkladnikID = 6,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 2.8f
                        },
                        new
                        {
                            WartoscOdzywczaID = 19,
                            SkladnikID = 7,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 1.1f
                        },
                        new
                        {
                            WartoscOdzywczaID = 20,
                            SkladnikID = 7,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 75f
                        },
                        new
                        {
                            WartoscOdzywczaID = 21,
                            SkladnikID = 7,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 15f
                        },
                        new
                        {
                            WartoscOdzywczaID = 22,
                            SkladnikID = 8,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 14f
                        },
                        new
                        {
                            WartoscOdzywczaID = 23,
                            SkladnikID = 8,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 0f
                        },
                        new
                        {
                            WartoscOdzywczaID = 24,
                            SkladnikID = 8,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 27f
                        },
                        new
                        {
                            WartoscOdzywczaID = 25,
                            SkladnikID = 9,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 0.1f
                        },
                        new
                        {
                            WartoscOdzywczaID = 26,
                            SkladnikID = 9,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 16.3f
                        },
                        new
                        {
                            WartoscOdzywczaID = 27,
                            SkladnikID = 9,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 1.8f
                        },
                        new
                        {
                            WartoscOdzywczaID = 28,
                            SkladnikID = 10,
                            SkladnikOdzywczyID = 2,
                            ZawartoscSkladnikOdzywczy = 0.2f
                        },
                        new
                        {
                            WartoscOdzywczaID = 29,
                            SkladnikID = 10,
                            SkladnikOdzywczyID = 3,
                            ZawartoscSkladnikOdzywczy = 2.9f
                        },
                        new
                        {
                            WartoscOdzywczaID = 30,
                            SkladnikID = 10,
                            SkladnikOdzywczyID = 1,
                            ZawartoscSkladnikOdzywczy = 1.4f
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.Zamowienie", b =>
                {
                    b.Property<int>("ZamowienieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataRealizacji")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataZlozenia")
                        .HasColumnType("datetime2");

                    b.Property<int>("KlientID")
                        .HasColumnType("int");

                    b.Property<string>("KodPocztowy")
                        .HasColumnType("varchar(5)");

                    b.Property<decimal>("Koszt")
                        .HasColumnType("money");

                    b.Property<string>("Miejscowosc")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NrBudynek")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("NrMieszkanie")
                        .HasColumnType("varchar(15)");

                    b.Property<int>("PlatnoscTypID")
                        .HasColumnType("int");

                    b.Property<int>("PozycjaMenuID")
                        .HasColumnType("int");

                    b.Property<int>("PracownikID")
                        .HasColumnType("int");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ZamowienieStatusID")
                        .HasColumnType("int");

                    b.HasKey("ZamowienieID");

                    b.HasIndex("KlientID");

                    b.HasIndex("PlatnoscTypID");

                    b.HasIndex("PozycjaMenuID");

                    b.HasIndex("PracownikID");

                    b.HasIndex("ZamowienieStatusID");

                    b.ToTable("Zamowienie");

                    b.HasData(
                        new
                        {
                            ZamowienieID = 1,
                            DataRealizacji = new DateTime(2020, 6, 3, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            DataZlozenia = new DateTime(2020, 6, 2, 13, 57, 32, 0, DateTimeKind.Unspecified),
                            KlientID = 1,
                            KodPocztowy = "01234",
                            Koszt = 31.5m,
                            Miejscowosc = "Warszawa",
                            NrBudynek = "1",
                            NrMieszkanie = "2",
                            PlatnoscTypID = 1,
                            PozycjaMenuID = 1,
                            PracownikID = 1,
                            Ulica = "Długa",
                            ZamowienieStatusID = 1
                        },
                        new
                        {
                            ZamowienieID = 2,
                            DataRealizacji = new DateTime(2020, 6, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DataZlozenia = new DateTime(2020, 6, 4, 17, 47, 42, 0, DateTimeKind.Unspecified),
                            KlientID = 2,
                            KodPocztowy = "43210",
                            Koszt = 30.5m,
                            Miejscowosc = "Wrocław",
                            NrBudynek = "14c",
                            NrMieszkanie = "-",
                            PlatnoscTypID = 2,
                            PozycjaMenuID = 2,
                            PracownikID = 1,
                            Ulica = "Miła",
                            ZamowienieStatusID = 3
                        },
                        new
                        {
                            ZamowienieID = 3,
                            DataRealizacji = new DateTime(2020, 6, 9, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            DataZlozenia = new DateTime(2020, 6, 8, 9, 7, 5, 0, DateTimeKind.Unspecified),
                            KlientID = 3,
                            KodPocztowy = "11222",
                            Koszt = 36.5m,
                            Miejscowosc = "Gdańsk",
                            NrBudynek = "12",
                            NrMieszkanie = "2",
                            PlatnoscTypID = 3,
                            PozycjaMenuID = 3,
                            PracownikID = 1,
                            Ulica = "Szeroka",
                            ZamowienieStatusID = 5
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.ZamowienieStatus", b =>
                {
                    b.Property<int>("ZamowienieStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazwaStatus")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ZamowienieStatusID");

                    b.ToTable("ZamowienieStatus");

                    b.HasData(
                        new
                        {
                            ZamowienieStatusID = 1,
                            NazwaStatus = "zamówione"
                        },
                        new
                        {
                            ZamowienieStatusID = 2,
                            NazwaStatus = "w trakcie przygotowywania"
                        },
                        new
                        {
                            ZamowienieStatusID = 3,
                            NazwaStatus = "przygotowane"
                        },
                        new
                        {
                            ZamowienieStatusID = 4,
                            NazwaStatus = "w trakcie dostawy"
                        },
                        new
                        {
                            ZamowienieStatusID = 5,
                            NazwaStatus = "dostarczone"
                        });
                });

            modelBuilder.Entity("SIZCapi.Models.InformacjaAlergen", b =>
                {
                    b.HasOne("SIZCapi.Models.Alergen", "Alergen")
                        .WithMany("InformacjaAlergen")
                        .HasForeignKey("AlergenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIZCapi.Models.Skladnik", "Skladnik")
                        .WithMany("InformacjaAlergen")
                        .HasForeignKey("SkladnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIZCapi.Models.Pracownik", b =>
                {
                    b.HasOne("SIZCapi.Models.PracownikRola", "PracownikRola")
                        .WithMany("Pracownik")
                        .HasForeignKey("PracownikRolaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIZCapi.Models.Skladnik", b =>
                {
                    b.HasOne("SIZCapi.Models.PozycjaMenu", "PozycjaMenu")
                        .WithMany("Skladnik")
                        .HasForeignKey("PozycjaMenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIZCapi.Models.WartoscOdzywcza", b =>
                {
                    b.HasOne("SIZCapi.Models.Skladnik", "Skladnik")
                        .WithMany("WartoscOdzywcza")
                        .HasForeignKey("SkladnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIZCapi.Models.SkladnikOdzywczy", "SkladnikOdzywczy")
                        .WithMany("WartoscOdzywcza")
                        .HasForeignKey("SkladnikOdzywczyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIZCapi.Models.Zamowienie", b =>
                {
                    b.HasOne("SIZCapi.Models.Klient", "Klient")
                        .WithMany("Zamowienie")
                        .HasForeignKey("KlientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIZCapi.Models.PlatnoscTyp", "PlatnoscTyp")
                        .WithMany("Zamowienie")
                        .HasForeignKey("PlatnoscTypID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIZCapi.Models.PozycjaMenu", "PozycjaMenu")
                        .WithMany("Zamowienie")
                        .HasForeignKey("PozycjaMenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIZCapi.Models.Pracownik", "Pracownik")
                        .WithMany("Zamowienie")
                        .HasForeignKey("PracownikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIZCapi.Models.ZamowienieStatus", "ZamowienieStatus")
                        .WithMany("Zamowienie")
                        .HasForeignKey("ZamowienieStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
